RETRIEVE_N=20
RERANK_CANDIDATES=10
FINAL_K=5

ROUTER_MODEL="openai/gpt-oss-20b"
GEN_MODEL="openai/gpt-oss-120b"

GEN_TEMPERATURE=0
GEN_MAX_TOKENS=700
MAX_CHUNK_CHARS=1800
NOT_FOUND="NOT_FOUND_IN_CONTRACT"

VERIFY_MODEL="openai/gpt-oss-20b"
VERIFY_TEMPERATURE=0

MAX_QUERY_CHARS=500
GUARD_MODEL="meta-llama/llama-prompt-guard-2-86m"
GUARD_INJECTION_THRESHOLD=0.5